# Generated by Django 5.1.15 on 2026-04-14 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Agendado (Beat)'), ('manual', 'Manual (API)'), ('nifi', 'Trigger NiFi')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('success', 'Sucesso'), ('partial', 'Parcial (com erros)'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('total_extracted', models.IntegerField(default=0, help_text='Total de registros extraídos')),
                ('total_transformed', models.IntegerField(default=0, help_text='Total após transformação')),
                ('total_loaded', models.IntegerField(default=0, help_text='Total carregados no destino')),
                ('total_errors', models.IntegerField(default=0, help_text='Total de erros')),
                ('total_skipped', models.IntegerField(default=0, help_text='Total ignorados (dedup)')),
                ('source', models.CharField(default='all', help_text='Fonte: all, se1426, eol_db, coresso', max_length=50)),
                ('target_realm', models.CharField(default='sme-apps', help_text='Realm Keycloak de destino', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, help_text='Observações da execução', null=True)),
                ('executed_by', models.CharField(blank=True, help_text='Usuário ou sistema que disparou', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Execução ETL',
                'verbose_name_plural': 'Execuções ETL',
                'db_table': 'etl_execution',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_exec_created'), models.Index(fields=['status'], name='idx_exec_status'), models.Index(fields=['source'], name='idx_exec_source')],
            },
        ),
        migrations.CreateModel(
            name='ETLStepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(choices=[('extract_se1426', '1. Extract SE1426'), ('extract_eol_db', '1b. Extract EOL_DB'), ('extract_coresso', '2. Extract CORESSO'), ('staging', '3. Staging Insert'), ('crossref_dedup', '4. Crossref / Dedup'), ('decision', '5. Decision (Create/Update)'), ('load_keycloak', '6. Load Keycloak'), ('load_token_ms', '7. Load token-ms'), ('audit', '8. Audit')], max_length=30)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='running', max_length=20)),
                ('records_in', models.IntegerField(default=0)),
                ('records_out', models.IntegerField(default=0)),
                ('records_error', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.etlexecution')),
            ],
            options={
                'verbose_name': 'Log de Etapa ETL',
                'verbose_name_plural': 'Logs de Etapas ETL',
                'db_table': 'etl_step_log',
                'ordering': ['execution', 'step_order'],
                'unique_together': {('execution', 'step_name')},
            },
        ),
        migrations.CreateModel(
            name='UpsertControl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'Usuário'), ('group', 'Grupo'), ('role', 'Role'), ('client', 'Client')], max_length=20)),
                ('source_system', models.CharField(help_text='Sistema de origem: se1426, eol_db, coresso', max_length=50)),
                ('source_id', models.CharField(help_text='ID do registro na fonte (RF, CPF, matrícula, etc.)', max_length=255)),
                ('target_id', models.CharField(blank=True, help_text='ID no destino (Keycloak user ID, etc.)', max_length=255, null=True)),
                ('target_realm', models.CharField(default='sme-apps', max_length=100)),
                ('content_hash', models.CharField(help_text='SHA-256 dos campos significativos', max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsert_records', to='core.etlexecution')),
            ],
            options={
                'verbose_name': 'Controle de Upsert',
                'verbose_name_plural': 'Controles de Upsert',
                'db_table': 'etl_upsert_control',
                'indexes': [models.Index(fields=['entity_type', 'source_system'], name='idx_upsert_entity_source'), models.Index(fields=['source_id'], name='idx_upsert_source_id'), models.Index(fields=['target_id'], name='idx_upsert_target_id'), models.Index(fields=['content_hash'], name='idx_upsert_hash')],
                'unique_together': {('entity_type', 'source_system', 'source_id', 'target_realm')},
            },
        ),
    ]
