# Generated by Django 5.2.15 on 2026-06-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SistemaStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coresso_sis_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "url_callback",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "url_logout",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("situacao", models.IntegerField(default=1)),
                (
                    "kc_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kc_client_uuid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "kc_realm",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "situacao_provisionamento",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("provisionado", "Provisionado"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("detalhe_erro", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staging_sistema",
            },
        ),
        migrations.CreateModel(
            name="PerfilCoressoStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coresso_gru_id",
                    models.CharField(
                        db_index=True, max_length=50, unique=True
                    ),
                ),
                ("coresso_sis_id", models.IntegerField(db_index=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "kc_role_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("situacao", models.IntegerField(default=1)),
                (
                    "situacao_provisionamento",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("provisionado", "Provisionado"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("detalhe_erro", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfis",
                        to="staging.sistemastaging",
                    ),
                ),
            ],
            options={
                "db_table": "staging_perfil_coresso",
            },
        ),
        migrations.CreateModel(
            name="UsuarioAlunoStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_execucao", models.UUIDField(db_index=True)),
                ("fonte", models.CharField(max_length=50)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("detalhe_erro", models.TextField(blank=True, null=True)),
                (
                    "lotacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "lotacao_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ue", models.CharField(blank=True, max_length=50, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cod_escola",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "turma",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "matricula",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "staging_usuario_aluno",
                "indexes": [
                    models.Index(
                        fields=["id_execucao", "situacao"],
                        name="staging_usu_id_exec_9ebe18_idx",
                    ),
                    models.Index(
                        fields=["cpf"], name="staging_usu_cpf_34f827_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsuarioServidorStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_execucao", models.UUIDField(db_index=True)),
                ("fonte", models.CharField(max_length=50)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("detalhe_erro", models.TextField(blank=True, null=True)),
                (
                    "lotacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "lotacao_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ue", models.CharField(blank=True, max_length=50, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "rf",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "matricula",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "funcao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "staging_usuario_servidor",
                "indexes": [
                    models.Index(
                        fields=["id_execucao", "situacao"],
                        name="staging_usu_id_exec_915766_idx",
                    ),
                    models.Index(
                        fields=["cpf"], name="staging_usu_cpf_ec2857_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsuarioTerceiroStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_execucao", models.UUIDField(db_index=True)),
                ("fonte", models.CharField(max_length=50)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("detalhe_erro", models.TextField(blank=True, null=True)),
                (
                    "lotacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "lotacao_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ue", models.CharField(blank=True, max_length=50, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_acesso",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "matricula",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "staging_usuario_terceiro",
                "indexes": [
                    models.Index(
                        fields=["id_execucao", "situacao"],
                        name="staging_usu_id_exec_f99434_idx",
                    ),
                    models.Index(
                        fields=["cpf"], name="staging_usu_cpf_a3ff22_idx"
                    ),
                ],
            },
        ),
    ]
