# Generated by Django 5.2.15 on 2026-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilcoressostaging",
            name="kc_role_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
