# Generated by Django 5.2.15 on 2026-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staging", "0002_perfilcoressostaging_kc_role_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioalunostaging",
            name="rf",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="usuarioterceirostaging",
            name="rf",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True
            ),
        ),
    ]
