# Generated by Django 5.2.17 on 2026-08-26 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staging", "0003_usuarioalunostaging_rf_usuarioterceirostaging_rf"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoServidorStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_execucao", models.UUIDField(db_index=True)),
                ("tipo_vinculo", models.CharField(max_length=20)),
                ("codigo_vinculo_origem", models.CharField(max_length=50)),
                (
                    "cargo_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cargo_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unidade_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "unidade_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dre_codigo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "situacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "data_inicio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vigente", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="staging.usuarioservidorstaging",
                    ),
                ),
            ],
            options={
                "db_table": "staging_vinculo_servidor",
                "indexes": [
                    models.Index(
                        fields=["id_execucao"],
                        name="staging_vin_id_exec_70a9bf_idx",
                    ),
                    models.Index(
                        fields=["servidor", "tipo_vinculo"],
                        name="staging_vin_servido_4a2ca4_idx",
                    ),
                ],
            },
        ),
    ]
