# Generated by Django 5.1.15 on 2026-04-14 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagingLotacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=500)),
                ('tipo', models.CharField(help_text='dre, ue, sme', max_length=20)),
                ('dre_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('dre_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('keycloak_group_path', models.CharField(blank=True, help_text='E.g. /SME/DRE-BT/EMEF-ABC', max_length=255, null=True)),
                ('keycloak_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staging Lotação',
                'verbose_name_plural': 'Staging Lotações',
                'db_table': 'staging_lotacao',
                'indexes': [models.Index(fields=['tipo'], name='idx_stg_lotacao_tipo'), models.Index(fields=['dre_codigo'], name='idx_stg_lotacao_dre')],
            },
        ),
        migrations.CreateModel(
            name='StagingPerfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargo_codigo', models.CharField(max_length=50)),
                ('cargo_nome', models.CharField(max_length=255)),
                ('funcao_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('funcao_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('keycloak_role', models.CharField(help_text='Nome da role Keycloak correspondente', max_length=100)),
                ('keycloak_group_path', models.CharField(blank=True, help_text='Path do grupo Keycloak, e.g. /SME/DRE-BT', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staging Perfil',
                'verbose_name_plural': 'Staging Perfis',
                'db_table': 'staging_perfil',
                'unique_together': {('cargo_codigo', 'funcao_codigo')},
            },
        ),
        migrations.CreateModel(
            name='StagingUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rf', models.CharField(blank=True, help_text='Registro Funcional', max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao', models.CharField(blank=True, help_text='Ativo/Inativo', max_length=50, null=True)),
                ('lotacao', models.CharField(blank=True, help_text='Código da UE/DRE', max_length=255, null=True)),
                ('lotacao_nome', models.CharField(blank=True, max_length=500, null=True)),
                ('dre', models.CharField(blank=True, max_length=100, null=True)),
                ('ue', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_escola', models.CharField(blank=True, max_length=20, null=True)),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('se1426', 'SE1426 (PRODAM)'), ('eol_db', 'EOL_DB'), ('coresso', 'CORESSO')], max_length=20)),
                ('status', models.CharField(choices=[('raw', 'Bruto (recém extraído)'), ('transformed', 'Transformado'), ('ready', 'Pronto para carga'), ('loaded', 'Carregado'), ('skipped', 'Ignorado (dedup)'), ('error', 'Erro')], default='raw', max_length=20)),
                ('execution_id', models.UUIDField(help_text='ID da execução ETL que extraiu este registro')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Payload original da fonte')),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('transformed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Staging Usuário',
                'verbose_name_plural': 'Staging Usuários',
                'db_table': 'staging_usuario',
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['rf'], name='idx_stg_usuario_rf'), models.Index(fields=['cpf'], name='idx_stg_usuario_cpf'), models.Index(fields=['source', 'status'], name='idx_stg_usuario_src_status'), models.Index(fields=['execution_id'], name='idx_stg_usuario_exec')],
            },
        ),
        migrations.CreateModel(
            name='DedupResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedup_key', models.CharField(db_index=True, help_text="Chave canônica: 'cpf:12345678901' ou 'rf:123456'", max_length=100)),
                ('match_type', models.CharField(choices=[('cpf_exact', 'CPF exato'), ('rf_exact', 'RF exato'), ('cpf_rf_cross', 'CPF↔RF cruzado (mesma pessoa, fontes diferentes)'), ('manual', 'Resolução manual')], max_length=20)),
                ('decision', models.CharField(choices=[('merge', 'Mesclar (enriquecer dados)'), ('keep_winner', 'Manter registro vencedor'), ('skip_duplicate', 'Ignorar duplicata'), ('conflict', 'Conflito (requer revisão)')], max_length=20)),
                ('merged_fields', models.JSONField(blank=True, default=list, help_text='Lista de campos enriquecidos do loser para o winner')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('rf', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('execution_id', models.UUIDField(db_index=True)),
                ('confidence', models.FloatField(default=1.0, help_text='Grau de confiança do match (1.0 = exato, <1.0 = heurístico)')),
                ('reviewed', models.BooleanField(default=False, help_text='Revisado manualmente?')),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(blank=True, help_text='Registro perdedor (marcado como SKIPPED)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedup_lost', to='staging.stagingusuario')),
                ('winner', models.ForeignKey(help_text='Registro vencedor (mantido para carga)', on_delete=django.db.models.deletion.CASCADE, related_name='dedup_won', to='staging.stagingusuario')),
            ],
            options={
                'verbose_name': 'Resultado de Deduplicação',
                'verbose_name_plural': 'Resultados de Deduplicação',
                'db_table': 'staging_dedup_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution_id', 'match_type'], name='idx_dedup_exec_type'), models.Index(fields=['decision'], name='idx_dedup_decision')],
            },
        ),
    ]
