# Generated by Django 5.1.15 on 2026-04-27 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0004_add_exec_status_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coresso_sis_id', models.IntegerField(db_index=True, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('url_callback', models.CharField(blank=True, max_length=2000, null=True)),
                ('url_logout', models.CharField(blank=True, max_length=2000, null=True)),
                ('tipo_autenticacao', models.IntegerField(blank=True, null=True)),
                ('situacao', models.IntegerField(default=1)),
                ('kc_client_id', models.CharField(blank=True, help_text='clientId no Keycloak (e.g. sgp-prod)', max_length=255, null=True)),
                ('kc_client_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('kc_realm', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('raw', 'Bruto (extraído)'), ('ready', 'Pronto p/ Keycloak'), ('loaded', 'Cliente criado no Keycloak'), ('error', 'Erro'), ('skipped', 'Pulado (inativo)')], default='raw', max_length=20)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staging Sistema',
                'verbose_name_plural': 'Staging Sistemas',
                'db_table': 'staging_sistema',
                'indexes': [models.Index(fields=['status'], name='idx_stg_sistema_status'), models.Index(fields=['sigla'], name='idx_stg_sistema_sigla')],
            },
        ),
    ]
