# Generated by Django 5.1.15 on 2026-04-27 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0005_stagingsistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroalimentacaoCoreSSO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('user_created', 'Usuário criado'), ('user_updated', 'Usuário atualizado'), ('role_assigned', 'Role atribuída'), ('role_revoked', 'Role revogada')], db_index=True, max_length=30)),
                ('rf', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('failed', 'Falha'), ('skipped', 'Pulado')], db_index=True, default='pending', max_length=20)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Retroalimentação CoreSSO',
                'verbose_name_plural': 'Retroalimentações CoreSSO',
                'db_table': 'retroalim_coresso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'tipo'], name='idx_retro_status_tipo')],
            },
        ),
        migrations.CreateModel(
            name='StagingPerfilCoreSSO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coresso_gru_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('coresso_sis_id', models.IntegerField(db_index=True)),
                ('coresso_vis_id', models.IntegerField(blank=True, null=True)),
                ('situacao', models.IntegerField(default=1)),
                ('kc_role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kc_role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('raw', 'Bruto'), ('ready', 'Pronto'), ('loaded', 'Role criada no Keycloak'), ('error', 'Erro')], default='raw', max_length=20)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='staging.stagingsistema')),
            ],
            options={
                'verbose_name': 'Staging Perfil CoreSSO',
                'verbose_name_plural': 'Staging Perfis CoreSSO',
                'db_table': 'staging_perfil_coresso',
                'indexes': [models.Index(fields=['coresso_sis_id'], name='idx_stg_perfco_sis'), models.Index(fields=['status'], name='idx_stg_perfco_status')],
            },
        ),
    ]
