# Generated by Django 5.2.15 on 2026-06-15 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckpointEtl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_execucao",
                    models.UUIDField(
                        help_text="UUID da ExecucaoETL associada", unique=True
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        help_text="Nome da etapa (nome_tarefa da spec)",
                        max_length=60,
                    ),
                ),
                (
                    "pagina_atual",
                    models.IntegerField(
                        default=0, help_text="Índice da página ao interromper"
                    ),
                ),
                (
                    "ultimo_id_processado",
                    models.CharField(
                        blank=True,
                        help_text="Último ID processado antes da interrupção",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "estado_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estado arbitrário da etapa para retomada",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Checkpoint ETL",
                "verbose_name_plural": "Checkpoints ETL",
                "db_table": "etl_checkpoint",
            },
        ),
        migrations.CreateModel(
            name="MarcaDaguaExtracao",
            fields=[
                (
                    "fonte",
                    models.CharField(
                        help_text="Identificador da fonte: se1426 | coresso | eol_alunos",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ultimo_processado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp do último registro processado com sucesso",
                        null=True,
                    ),
                ),
                (
                    "ultima_pagina",
                    models.IntegerField(
                        default=0,
                        help_text="Última página processada na extração paginada",
                    ),
                ),
                (
                    "total_processado",
                    models.IntegerField(
                        default=0,
                        help_text="Total acumulado de registros processados",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marca D'Água de Extração",
                "verbose_name_plural": "Marcas D'Água de Extração",
                "db_table": "etl_marca_dagua_extracao",
            },
        ),
        migrations.CreateModel(
            name="SistemaProvisionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coresso_sis_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "url_callback",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "url_logout",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("situacao", models.IntegerField(default=1)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "etl_sistema_provisionado",
            },
        ),
        migrations.CreateModel(
            name="ExecucaoETL",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "id_execucao",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        default="todos",
                        help_text="Fonte: todos | se1426 | coresso | eol_alunos",
                        max_length=20,
                    ),
                ),
                (
                    "realm_destino",
                    models.CharField(default="sme-apps", max_length=100),
                ),
                (
                    "tipo_disparo",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado (Beat)"),
                            ("manual", "Manual (API)"),
                        ],
                        default="agendado",
                        max_length=20,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("executando", "Executando"),
                            ("sucesso", "Sucesso"),
                            ("parcial", "Parcial (com erros)"),
                            ("falha", "Falha"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("total_extraido", models.IntegerField(default=0)),
                ("total_transformado", models.IntegerField(default=0)),
                ("total_carregado", models.IntegerField(default=0)),
                ("total_erros", models.IntegerField(default=0)),
                ("total_ignorados", models.IntegerField(default=0)),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_tarefa_celery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "disparado_por",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Execução ETL",
                "verbose_name_plural": "Execuções ETL",
                "db_table": "etl_execucao",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["-criado_em"], name="idx_execucao_criado"
                    ),
                    models.Index(
                        fields=["situacao"], name="idx_execucao_situacao"
                    ),
                    models.Index(fields=["fonte"], name="idx_execucao_fonte"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RastreioTentativa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_execucao", models.UUIDField(db_index=True)),
                ("nome_tarefa", models.CharField(max_length=60)),
                ("numero_tentativa", models.PositiveSmallIntegerField()),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("erro", models.TextField(blank=True, null=True)),
                ("duracao_segundos", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rastreio de Tentativa",
                "verbose_name_plural": "Rastreios de Tentativas",
                "db_table": "etl_rastreio_tentativa",
                "indexes": [
                    models.Index(
                        fields=["id_execucao", "nome_tarefa"],
                        name="idx_rastreio_exec_tarefa",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerfilProvisionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coresso_gru_id",
                    models.CharField(
                        db_index=True, max_length=50, unique=True
                    ),
                ),
                ("coresso_sis_id", models.IntegerField(db_index=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "kc_role_nome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("situacao", models.IntegerField(default=1)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfis",
                        to="controle_etl.sistemaprovisionado",
                    ),
                ),
            ],
            options={
                "db_table": "etl_perfil_provisionado",
            },
        ),
        migrations.CreateModel(
            name="ControleProvisionamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tipo_entidade",
                    models.CharField(
                        choices=[
                            ("usuario", "Usuário"),
                            ("grupo", "Grupo"),
                            ("role", "Role"),
                            ("client", "Client"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sistema_origem",
                    models.CharField(
                        help_text="Sistema de origem: se1426, coresso",
                        max_length=50,
                    ),
                ),
                (
                    "id_origem",
                    models.CharField(
                        help_text="Identificador na fonte (RF, CPF, matrícula)",
                        max_length=255,
                    ),
                ),
                (
                    "id_destino",
                    models.CharField(
                        blank=True,
                        help_text="ID no Keycloak",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "realm_destino",
                    models.CharField(default="sme-apps", max_length=100),
                ),
                (
                    "hash_conteudo",
                    models.CharField(
                        help_text="SHA-256 dos campos significativos",
                        max_length=64,
                    ),
                ),
                ("versao", models.PositiveIntegerField(default=1)),
                ("sincronizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "erro_sincronizacao",
                    models.TextField(blank=True, null=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ultima_execucao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_provisionamento",
                        to="controle_etl.execucaoetl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle de Provisionamento",
                "verbose_name_plural": "Controles de Provisionamento",
                "db_table": "etl_controle_provisionamento",
                "indexes": [
                    models.Index(
                        fields=["tipo_entidade", "sistema_origem"],
                        name="idx_prov_entidade_sistema",
                    ),
                    models.Index(
                        fields=["id_origem"], name="idx_prov_id_origem"
                    ),
                    models.Index(
                        fields=["hash_conteudo"], name="idx_prov_hash"
                    ),
                ],
                "unique_together": {
                    (
                        "tipo_entidade",
                        "sistema_origem",
                        "id_origem",
                        "realm_destino",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="LogEtapaETL",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "nome_etapa",
                    models.CharField(
                        choices=[
                            (
                                "task_identidade_extrair_se1426",
                                "1. Extrair SE1426",
                            ),
                            (
                                "task_identidade_extrair_coresso",
                                "2. Extrair CoreSSO",
                            ),
                            (
                                "task_identidade_extrair_eol_alunos",
                                "2b. Extrair EOL Alunos",
                            ),
                            (
                                "task_identidade_resolver_identidade",
                                "3. Resolver Identidade",
                            ),
                            (
                                "task_provisionar_identidade_keycloak",
                                "4. Provisionar Keycloak",
                            ),
                            (
                                "task_carregar_atributos_token",
                                "5. Carregar Atributos Token",
                            ),
                            ("task_sync_rec_etl", "6. Registro Operacional"),
                        ],
                        max_length=60,
                    ),
                ),
                ("ordem_etapa", models.PositiveSmallIntegerField()),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("executando", "Executando"),
                            ("sucesso", "Sucesso"),
                            ("falha", "Falha"),
                            ("ignorado", "Ignorado"),
                        ],
                        default="executando",
                        max_length=20,
                    ),
                ),
                ("registros_entrada", models.IntegerField(default=0)),
                ("registros_saida", models.IntegerField(default=0)),
                ("registros_erro", models.IntegerField(default=0)),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                ("detalhe_erro", models.TextField(blank=True, null=True)),
                ("metadados", models.JSONField(blank=True, default=dict)),
                (
                    "execucao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="controle_etl.execucaoetl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Etapa ETL",
                "verbose_name_plural": "Logs de Etapas ETL",
                "db_table": "etl_log_etapa",
                "ordering": ["execucao", "ordem_etapa"],
                "unique_together": {("execucao", "nome_etapa")},
            },
        ),
    ]
