# Generated by Django 5.2.15 on 2026-06-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle_etl", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerfilProvisionado",
        ),
        migrations.DeleteModel(
            name="SistemaProvisionado",
        ),
    ]
