# Generated by Django 5.2.16 on 2026-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_etl", "0003_hash_multi_estagio"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleprovisionamento",
            name="token_ms_pendente",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True quando hash_token_ms está desatualizado em relação ao dado atual — permite localizar pendências de envio ao token-ms sem depender do staging de uma execução específica (que é limpo periodicamente).",
            ),
        ),
        migrations.AlterField(
            model_name="controleprovisionamento",
            name="realm_destino",
            field=models.CharField(default="COTIC", max_length=100),
        ),
        migrations.AlterField(
            model_name="execucaoetl",
            name="realm_destino",
            field=models.CharField(default="COTIC", max_length=100),
        ),
    ]
